{{- if .Values.clusterReaderRole.enable -}}
  {{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRoleBinding" "" .Values.clusterReaderRole.name) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterReaderRole.name }}
  labels:
    {{- include "cluster-rbac.labels" . | nindent 4 }}
  {{- with .Values.clusterReaderRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.clusterReaderRole.name }}
subjects:
- kind: Group
  name: {{ .Values.clusterReaderRole.groupObjectId }}
  {{- end }}
{{- end }}