{{- if ((.Values.clusterReaderRole).enabled) | default true -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ ((.Values.clusterReaderRole).name) | default "cluster-reader" }}
  labels:
    {{- include "cluster-rbac.labels" . | nindent 4 }}
  {{- with ((.Values.clusterReaderRole).annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ ((.Values.clusterReaderRole).name) | default "cluster-reader" }}
subjects:
- kind: Group
  name: {{ ((.Values.clusterReaderRole).groupObjectId) | default "objectID" }}
  {{- end }}
{{- end }}