{{- if ((.Values.clusterAuditRole).enabled) | default true -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ ((.Values.clusterAuditRole).name) | default "cluster-audit" }}
  labels:
    {{- include "cluster-rbac.labels" . | nindent 4 }}
  {{- with ((.Values.clusterAuditRole).annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources:
  - componentstatuses
  - deployments
  - replicasets
  - pods
  - services
  - daemonsets
  - statefulset
  - jobs
  - cronjobs
  - secrets
  - configmaps
  - ingresses
  - serviceaccounts
  - resourcequotas
  - bindings
  - endpoints
  - events
  - namespaces
  - limitranges
  - nodes 
  - persistentvolumeclaims
  - persistentvolumes
  - podtemplates 
  - replicationcontrollers 
  - mutatingwebhookconfigurations 
  - validatingwebhookconfigurations 
  - customresourcedefinitions
  - apiservices
  - aplogconfs
  - appolicies
  - apusersigs
  - apdoslogconfs 
  - apdospolicies 
  - dosprotectedresources 
  - controllerrevisions 
  - tokenreviews
  - localsubjectaccessreviews
  - selfsubjectaccessreviews
  - selfsubjectrulesreviews
  - subjectaccessreviews
  - horizontalpodautoscalers
  - certificatesigningrequests
  - leases
  - endpointslices
  - flowschemas
  - prioritylevelconfigurations 
  - ingressclasses 
  - ingresses 
  - networkpolicies
  - runtimeclasses 
  - poddisruptionbudgets
  - podsecuritypolicies
  - clusterrolebindings
  - clusterroles
  - priorityclasses
  - volumesnapshotclasses
  - volumesnapshotcontents 
  - volumesnapshots
  - storageclasses 
  - volumeattachments
  - statefulsets 
  - configs 
  - providers 
  - dnsendpoints 
  - helmreleases 
  - globalconfigurations 
  - policies 
  - transportservers 
  - virtualserverroutes 
  - virtualservers 
  - kustomizations 
  - assign 
  - assignmetadata 
  - modifyset 
  - alerts 
  - providers 
  - receivers 
  - buckets 
  - gitrepositories 
  - helmcharts 
  - helmrepositories 
  - ocirepositories 
  - azurekeyvaultsecrets 
  - constraintpodstatuses 
  - constrainttemplatepodstatuses 
  - mutatorpodstatuses 
  - csidrivers 
  - csinodes 
  - csistoragecapacities 
  - constrainttemplates 
  - clusterpolicies 
  - clusterpolicyreports 
  - clusterreportchangerequests 
  - generaterequests 
  - policyreports 
  - reportchangerequests 
  - updaterequests
  - alertmanagerconfigs
  - alertmanagers
  - authorizationpolicies
  - backendconfigs
  - backups
  - backupstoragelocations
  - capacityrequests
  - certificaterequests
  - certificates
  - challenges
  - clusterissuers
  - clustertriggerauthentications
  - deletebackuprequests
  - destinationrules
  - downloadrequests
  - envoyfilters
  - frontendconfigs
  - gateways
  - issuers
  - istiooperators
  - jaegers
  - kialis
  - managedcertificates
  - orders
  - peerauthentications
  - podmonitors
  - podvolumebackups
  - podvolumerestores
  - probes
  - prometheuses
  - prometheusrules
  - proxyconfigs
  - requestauthentications
  - resticrepositories
  - restores
  - scaledjobs
  - scaledobjects
  - schedules
  - serverstatusrequests
  - serviceattachments
  - serviceentries
  - servicemonitors
  - servicenetworkendpointgroups
  - sidecars
  - storagestates
  - storageversionmigrations
  - telemetries
  - thanosrulers
  - triggerauthentications
  - updateinfos
  - virtualservices
  - volumesnapshotlocations
  - wasmplugins
  - workloadentries
  - workloadgroups
  verbs:
  - watch
  - list
- apiGroups: ["rbac.authorization.k8s.io"] # Authorization API group
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - get
  - list
  - watch
  {{- end }}
{{- end }}
