{{- if ((.Values.clusterAuditRole).enabled) | default true -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ ((.Values.clusterAuditRole).name) | default "cluster-audit" }}
  labels:
    {{- include "cluster-rbac.labels" . | nindent 4 }}
  {{- with ((.Values.clusterAuditRole).annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ ((.Values.clusterAuditRole).name) | default "cluster-audit" }}
subjects:
- kind: Group
  name: {{ ((.Values.clusterAuditRole).groupObjectId) | default "objectID" }}
  {{- end }}
{{- end }}