{{- range $name, $tenant := .Values.tenants }}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bootstrap
  namespace: {{ $name }}
spec:
  interval: 5m
  url: https://benchmarkconsulting.github.io/helm-bootstrap
  ---
  apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ $name }}
  namespace: {{ $name }}
spec:
  releaseName: {{ $name }}
  chart:
    spec:
      chart: namespace-bootstrap
      sourceRef:
        kind: HelmRepository
        name: bootstrap
        namespace: {{ $name }}
      version: 0.1.0
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
---
{{- end }} 
