{{- range $name, $tenant := .Values.tenants }}
apiVersion: v1
kind: Secret
metadata:
  name: artifactory-secret
  labels:
    platform/type: tenant
    {{- include "tenant-provision.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: fsfsdgretrgbghtyt453rfdgfhjyi87654tgh=
{{- end }}