{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $secret := $tenantConfig.secret | default dict -}}
{{- if (($secret.akv2k8sSecret).enabled) | default false -}}
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ default "artifactory-secret-sync" (($secret.akv2k8sSecret).name) }}
  namespace: {{ $name }}
  labels:
    platform/type: tenant
spec:
  vault:
    name: {{ default "akv2k8s-test" (($secret.akv2k8sSecret).vault.name) }} # name of key vault
    object:
      name: {{ default "my-secret" (($secret.akv2k8sSecret).object.name) }} # name of the akv object
      type: {{ default "secret" (($secret.akv2k8sSecret).object.type) }} # akv object type
  output: 
    secret: 
      name: {{ default "my-secret-from-akv" (($secret.akv2k8sSecret).secret.name) }}  # kubernetes secret name
      dataKey: {{ default "secret-value" (($secret.akv2k8sSecret).secret.dataKey) }}  # key to store object value in kubernetes secret
  {{- end }}
---
{{- end }}