{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $secret := $tenantConfig.secret | default dict -}}
{{- if (($secret.akv_eso).enabled) | default false -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ default "akv-secret-store" (($secret.akv_eso).name) }}
  namespace: {{ $name }}
  labels:
    platform/type: tenant
spec:
  provider:
    # provider type: azure keyvault
    azurekv:
      # azure tenant ID, see: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant
      tenantId: {{ default "65b6be73-2104-4ff4-899f-5bff3196f3d1" (($secret.akv_eso).tenantId) }}
      # URL of your vault instance, see: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: {{ default "https://akv2k8s-test-jc-2.vault.azure.net" (($secret.akv_eso).vaultUrl) }}
      authSecretRef:
        # points to the secret that contains
        # the azure service principal credentials
        clientId:
          name: {{ default "azure-secret-sp" (($secret.akv_eso).clientId.name) }}
          key: {{ default "ClientID" (($secret.akv_eso).clientId.key) }} 
        clientSecret:
          name: {{ default "azure-secret-sp" (($secret.akv_eso).clientSecret.name) }} 
          key: {{ default "ClientSecret" (($secret.akv_eso).clientSecret.key) }} 
  {{- end }}
---
{{- end }}