{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $secret := $tenantConfig.secret | default dict -}}
{{- if (($secret.eso).enabled) | default false -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ default "azure-secret-store" (($secret.eso).azure_secret_store_name) }}
  namespace: {{ $name }}
  labels:
    platform/type: tenant
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ default "https://example.vault.azure.net" (($secret.eso).azure_vaultUrl) }}
      serviceAccountRef:
        name: secretstore-sa
         
  {{- end }}
---
{{- end }}