{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $deployment := $tenantConfig.deployment | default dict -}}
{{- if (($deployment.spn).enabled) | default false -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-spn-rb
  namespace: {{ $name }}
  labels:
    platform/type: tenant
    {{- include "tenant-provision.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deploy-spn
subjects:
- kind: User
  namespace:  {{ $name }}
  name: {{ default "." (($deployment.spn).objectID) }}
  {{- end }}
---
{{- end }}
