{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $secret := $tenantConfig.secret | default dict -}}
{{- if (($secret.eso).enabled) | default false -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secretstore-sa
  namespace: {{ $name }}
  annotations:
    azure.workload.identity/client-id: {{ default "managed_identity_client_id" (($secret.eso).azure_managed_identity_client_id) }}
    azure.workload.identity/tenant-id: {{ default "azure_tenant_id" (($secret.eso).azure_tenant_id) }}
---
  {{- end }}
{{- end }}