{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $flux := $tenantConfig.flux | default dict -}}
{{- if (($flux.fluxRBAC).enabled) | default true -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  namespace: {{ $name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-rb
  namespace: {{ $name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-owner
subjects:
  - name: flux
    namespace: {{ $name }}
    kind: ServiceAccount
  {{- end }}
---
{{- end }}