{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $flux := $tenantConfig.flux | default dict -}}
{{- if (($flux.fluxConfig).enabled) | default false -}}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: {{ $name }}
  namespace: {{ $name }}
spec:
  interval: 30m
  url: https://github.com/benchmarkconsulting/helm-bootstrap/tree/main
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: {{ $name }}
  namespace: {{ $name }}
spec:
  interval: 1h
  path: {{ default "./$name" $flux.path }}
  prune: true
  serviceAccountName: flux
  targetNamespace: {{ $name }}
  sourceRef:
    kind: GitRepository
    name: {{ $name }}
    namespace: {{ $name }}
  {{- end }}
---
{{- end }}