{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $flux := $tenantConfig.flux | default dict -}}
{{- if (($flux.fluxConfig).enabled) | default false -}}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: {{ $name }}
  namespace: {{ $name }}
  labels:
    platform/type: tenant
spec:
  interval: 30m
  url: {{ default "." $flux.fluxConfig.url }}
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: {{ $name }}
  namespace: {{ $name }}
  labels:
    platform/type: tenant
spec:
  interval: 1h
  path: {{ default "./{{ $name }}" (($flux.fluxConfig).path) }}
  prune: true
  serviceAccountName: flux
  targetNamespace: {{ $name }}
  sourceRef:
    kind: GitRepository
    name: {{ $name }}
    namespace: {{ $name }}
---
  {{- end }}
{{- end }}