{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $secret := $tenantConfig.secret | default dict -}}
{{- if (($secret.eso).enabled) | default false -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ default "vault-secret-store" (($secret.eso).hc_vault_secret_store_name) }}
  namespace: {{ $name }}
  labels:
    platform/type: tenant
spec:
  provider:
    vault:
      server: {{ default "http://0.0.0.0:8200" (($secret.eso).hc_vault_server) }}
      path: {{ default "path_name" (($secret.vault_eso).hc_vault_secret_path) }}
      version: {{ default "v2" (($secret.vault_eso).hc_vault_kv_version) }}
      auth:
        jwt:
          path: {{ default "cluster_name" (($secret.vault_eso).hc_vault_jwt_auth_path) }}
          role: {{ default "role_name" (($secret.vault_eso).hc_vault_jwt_role) }}
          kubernetesServiceAccountToken:
            serviceAccountRef:
              name: "secretstore-sa"
            audiences:
            - vault
  {{- end }}
---
{{- end }}