{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $secret := $tenantConfig.secret | default dict -}}
{{- if (($secret.vault_eso).enabled) | default false -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ default "vault-backend-kubernetes" (($secret.vault_eso).name) }}
  namespace: {{ $name }}
  labels:
    platform/type: tenant
spec:
  provider:
    vault:
      server: {{ default "http://0.0.0.0:8200" (($secret.vault_eso).server) }}
      path: {{ default "new-way" (($secret.vault_eso).path) }}
      version: {{ default "v1" (($secret.vault_eso).version) }}
      auth:
        # Authenticate against Vault using a Kubernetes ServiceAccount
        # token stored in a Secret.
        # https://www.vaultproject.io/docs/auth/kubernetes
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "kubernetes"
          # A required field containing the Vault Role to assume.
          role: {{ default "eso-tenant4a" (($secret.vault_eso).role) }}
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          serviceAccountRef:
            name: "eso-sa"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eso-rb
  namespace: {{ $name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - name: eso-sa
    namespace: {{ $name }}
    kind: ServiceAccount
  {{- end }}
---
{{- end }}