{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $flux := $tenantConfig.flux | default dict -}}
{{- if (($flux.helmRepo).enabled) | default true -}}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: "global-artifactory-{{ $name }}"
  namespace: {{ $name }}
  labels:
    platform/type: tenant
spec:
  interval: 1m
  url: https://artifactory.platform.manulife.io/artifactory/helm
  {{- end }}
---
{{- end }}