{{- range $name, $tenant := .Values.tenants }}
{{- if not (lookup "v1" "Namespace" "" $name) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
  labels:
    platform/type: tenant
    {{- include "tenant-provision.labels" $ | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
{{- end }}
---
{{- end }}

