{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $namespace := $tenantConfig.namespace | default dict -}}
{{- define "ns" -}}
{{- $ns := lookup "v1" "Namespace" "" $name -}}
{{- if $ns := true -}}
{{- ($namespace.enabled) := false -}}
{{- else -}}
{{- ($namespace.enabled) := true -}}
{{- if ($namespace.enabled) -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
  labels:
    platform/type: tenant
    {{- include "tenant-provision.labels" $ | nindent 4 }}
  {{- end }}
 {{- end }}
---
{{- end }}