{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $namespace := $tenantConfig.namespace | default dict -}}
{{- if ($namespace.create) | default false -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
  labels:
    platform/type: tenant
    {{- include "tenant-provision.labels" $ | nindent 4 }}
 {{- end }}
---
{{- end }}