{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $quotas := $tenantConfig.quotas | default dict -}}
{{- if (($quotas.quotaCounts).enabled) | default false -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  namespace: {{ $name }}
  labels:
    platform/type: tenant
    {{- include "tenant-provision.labels" $ | nindent 4 }}
spec:
  hard:
    configmaps: {{ default 100 (($quotas.quotaCounts).configmaps) }}
    persistentvolumeclaims: {{ default 100 (($quotas.quotaCounts).persistentvolumeclaims) }}
    pods: {{ default 100 (($quotas.quotaCounts).pods) }}
    replicationcontrollers: {{ default 100 (($quotas.quotaCounts).replicationcontrollers) }}
    secrets: {{ default 100 (($quotas.quotaCounts).secrets) }}
    services: {{ default 100 (($quotas.quotaCounts).services) }}
  {{- end }}
---
{{- end }}
