{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $flux := $tenantConfig.flux | default dict -}}
{{- if (($flux.resourceQuota).enabled) | default false -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu
  namespace: {{ $name }}
  labels:
    platform/type: tenant
    {{- include "tenant-provision.labels" $ | nindent 4 }}
spec:
  hard:
    requests.cpu: {{ $flux.resourceQuota.requests.cpu | default 1 }} 
    requests.memory: {{ $flux.resourceQuota.requests.memory | default "1Gi" }}
    limits.cpu: {{ $flux.resourceQuota.limits.cpu | default 2 }}
    limits.memory: {{ $flux.resourceQuota.limits.memory | default "2Gi" }}
  {{- end }}
---
{{- end }}

