{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $flux := $tenantConfig.flux | default dict -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu
  namespace: {{ $name }}
  labels:
    {{- include "tenant-provision.labels" . | nindent 4 }}
  annotations:
    {{- toYaml . | nindent 4 }}
spec:
  hard:
    requests.cpu: 1
    requests.memory: 1Gi
    limits.cpu: 2
    limits.memory: 2Gi
{{- end }}

