{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $quotas := $tenantConfig.quotas | default dict -}}
{{- if (($quotas.quotaCounts).enabled) | default false -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  namespace: {{ $name }}
  labels:
    platform/type: tenant
    {{- include "tenant-provision.labels" $ | nindent 4 }}
spec:
  hard:
    configmaps: {{ $quotas.quotaCounts.configmaps | default 100 }}
    persistentvolumeclaims: {{ $quotas.quotaCounts.persistentvolumeclaims | default 100 }}
    pods: {{ $quotas.quotaCounts.pods | default 100 }}
    replicationcontrollers: {{ $quotas.quotaCounts.replicationcontrollers | default 100 }}
    secrets: {{ $quotas.quotaCounts.secrets | default 100 }}
    services: {{ $quotas.quotaCounts.services | default 100 }}
  {{- end }}
---
{{- end }}
