{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $quotas := $tenantConfig.quotas | default dict -}}
{{- if (($quotas.resourceQuota).enabled) | default false -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu
  namespace: {{ $name }}
  labels:
    platform/type: tenant
    {{- include "tenant-provision.labels" $ | nindent 4 }}
spec:
  hard:
    requests.cpu: {{ default 10 ((($quotas.resourceQuota).requests).cpu) }}
    requests.memory: {{ default "10Gi" ((($quotas.resourceQuota).requests).memory) }}
    limits.cpu: {{ default 20 ((($quotas.resourceQuota).limits).cpu) }}
    limits.memory: {{ default "20Gi" ((($quotas.resourceQuota).limits).memory) }}
---  
  {{- end }}
{{- end }}