{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $quotas := $tenantConfig.quotas | default dict -}}
{{- if (($quotas.resourceQuota).enabled) | default false -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu
  namespace: {{ $name }}
  labels:
    platform/type: tenant
    {{- include "tenant-provision.labels" $ | nindent 4 }}
spec:
  hard:
    requests.cpu: {{ $quotas.resourceQuota.requests.cpu | default 1 }} 
    requests.memory: {{ $quotas.resourceQuota.requests.memory | default "1Gi" }}
    limits.cpu: {{ $quotas.resourceQuota.limits.cpu | default 2 }}
    limits.memory: {{ $quotas.resourceQuota.limits.memory | default "2Gi" }}
  {{- end }}
---
{{- end }}

