{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $deployment := $tenantConfig.deployment | default dict -}}
{{- if (($deployment.serviceaccount).enabled) | default false -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "deploy-sa" (($deployment.serviceaccount).name) }}
  namespace: {{ $name }}
  labels:
    platform/type: tenant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ default "deploy-rb" (($deployment.serviceaccount.roleBinding).name) }}
  namespace: {{ $name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-admin
subjects:
  - name: {{ default "deploy-sa" (($deployment.serviceaccount).name) }}
    namespace: {{ $name }}
    kind: ServiceAccount
  {{- end }}
---
{{- end }}