{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $serviceaccount := $tenantConfig.serviceaccount | default dict -}}
{{- if ($serviceaccount.enabled) | default true -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceaccount.name | default "{{ $name }}-sa" }}
  namespace: {{ $name }}
  labels:
    platform/type: tenant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $serviceaccount.name | default "{{ $name }}-sa" }}
  namespace: {{ $name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-admin
subjects:
  - name: {{ $serviceaccount.name | default "{{ $name }}-sa" }}
    namespace: {{ $name }}
    kind: ServiceAccount
  {{- end }}
---
{{- end }}