{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $flux := $tenantConfig.flux | default dict -}}
{{- if (($flux.serviceAccount).enabled) | default false -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-sa
  namespace: {{ $name }}
  labels:
    platform/type: tenant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-rb
  namespace: {{ $name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-admin
subjects:
  - name: deploy-sa
    namespace: {{ $name }}
    kind: ServiceAccount
  {{- end }}
---
{{- end }}