{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $rbac := $tenantConfig.rbac | default dict -}}
{{- if (($rbac.tenantReaderRole).enabled) | default true -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-reader-rb
  namespace: {{ $name }}
  labels:
    platform/type: tenant
    {{- include "tenant-provision.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-reader
subjects:
- kind: Group
  namespace:  {{ $name }}
  name: {{ default "" (($rbac.tenantReaderRole).groupObjectId) }}
  {{- end }}
---
{{- end }}

