{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $flux := $tenantConfig.flux | default dict -}}
{{- if (($flux.tenantAuditRole).enabled) | default true -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-audit
  namespace: {{ $name }}
  labels:
    platform/type: tenant
    {{- include "tenant-provision.labels" $ | nindent 4 }}
rules:
- apiGroups: ["", "apps", "admissionregistration.k8s.io", "autoscaling", "batch", "certificates.k8s.io", "helm.toolkit.fluxcd.io", "metrics.k8s.io", "networking.k8s.io", "notification.toolkit.fluxcd.io", "policy", "rbac.authorization.k8s.io", "source.toolkit.fluxcd.io", "spv.no", "storage.k8s.io", "kyverno.io", "wgpolicyk8s.io", "kustomize.toolkit.fluxcd.io" ] # "" indicates the core API group
  resources:
  - bindings
  - componentstatuses
  - configmaps
  - endpoints
  - events
  - limitranges
  - namespaces
  - nodes
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - podtemplates
  - replicationcontrollers
  - resourcequotas
  - secrets
  - serviceaccounts
  - services
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  - controllerrevisions
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  - horizontalpodautoscalers
  - cronjobs
  - jobs
  - certificatesigningrequests
  - configs
  - events
  - helmreleases
  - kustomizations
  - nodes
  - pods
  - ingressclasses
  - ingresses
  - networkpolicies
  - alerts
  - receivers
  - poddisruptionbudgets
  - podsecuritypolicies
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  - buckets
  - gitrepositories
  - helmcharts
  - helmrepositories
  - ocirepositories
  - azurekeyvaultsecrets
  - csidrivers
  - csinodes
  - csistoragecapacities
  - storageclasses
  - volumeattachments
  - constrainttemplates
  verbs:
  - get
  - list 
  - watch 
  {{- end }}
---
{{- end }}
