{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $rbac := $tenantConfig.rbac | default dict -}}
{{- if (($rbac.tenantDevRole).enabled) | default true -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-dev
  namespace: {{ $name }}
  labels:
    platform/type: tenant
    {{- include "tenant-provision.labels" $ | nindent 4 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - bindings
  - configmaps
  - endpoints
  - events
  - limitranges
  - persistentvolumeclaims
  - pods
  - podtemplates
  - replicationcontrollers
  - resourcequotas
  - secrets
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups: ["apps"] #Other Core functions API groups
  resources:
  - controllerrevisions                    
  - daemonsets                
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups: ["autoscaling"] #Other Core functions API groups
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups: ["batch"] #Other Core functions API groups
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups: ["policy"] #Other Core functions API groups
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups: ["metrics.k8s.io"] # Extended core API groups
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups: ["networking.k8s.io" ] # Extended core API groups
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups: ["helm.toolkit.fluxcd.io"] # Flux API groups
  resources:
  - helmreleases
  verbs:
  - get
  - list
  - watch
- apiGroups: ["source.toolkit.fluxcd.io"] # Flux API groups
  resources:
  - buckets
  - gitrepositories
  - helmcharts
  - helmrepositories 
  verbs:
  - get
  - list
  - watch
- apiGroups: ["kustomize.toolkit.fluxcd.io"] # Flux API groups
  resources:
  - kustomizations
  verbs:
  - get
  - list
  - watch
- apiGroups: ["notification.toolkit.fluxcd.io"] # Flux API groups
  resources:
  - alerts
  - providers
  - receivers
  verbs:
  - get
  - list
  - watch
- apiGroups: ["storage.k8s.io"] # Storage API group
  resources:
  - csistoragecapacities
  verbs:
  - get
  - list
  - watch
- apiGroups: ["snapshot.storage.k8s.io"] # Storage API group
  resources:
  - volumesnapshots 
  verbs:
  - get
  - list
  - watch
- apiGroups: ["coordination.k8s.io"] # Coordination API group
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
- apiGroups: ["discovery.k8s.io"] # Discovery API group
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups: ["rbac.authorization.k8s.io"] # Authorization API group
  resources:
  - localsubjectaccessreviews
  - rolebindings
  - roles
  verbs:
  - get
  - list
  - watch
- apiGroups: ["authorization.k8s.io"] # Authorization API group
  resources:
  - localsubjectaccessreviews
  verbs:
  - get
  - list
  - watch
- apiGroups: ["spv.no"] # spv.no API group
  resources:
  - azurekeyvaultsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups: ["kyverno.io"] # kyverno API group
  resources:
  - generaterequests
  - policies
  - reportchangerequests
  - updaterequests
  verbs:
  - get
  - list
  - watch
- apiGroups: ["wgpolicyk8s.io"] # kyverno API group
  resources:
  - policyreports
  verbs:
  - get
  - list
  - watch
- apiGroups: ["cert-manager.io"] # cert-manager API group
  resources:
  - certificaterequests
  - certificates
  verbs:
  - get
  - list
  - watch
- apiGroups: ["acme.cert-manager.io"] # cert-manager API group
  resources:
  - challenges
  - issuers
  - orders
  verbs:
  - get
  - list
  - watch
- apiGroups: ["install.istio.io"] # Istio API group
  resources:
  - istiooperators
  verbs:
  - get
  - list
  - watch
- apiGroups: ["security.istio.io"] # Istio API group
  resources:
  - peerauthentications
  - authorizationpolicies
  - requestauthentications
  verbs:
  - get
  - list
  - watch
- apiGroups: ["networking.istio.io"] # Istio API group
  resources:
  - destinationrules
  - envoyfilters
  - gateways
  - proxyconfigs
  - serviceentries
  - sidecars
  - virtualservices
  - workloadentries
  - workloadgroups
  verbs:
  - get
  - list
  - watch
- apiGroups: ["config.istio.io"] # Istio API group
  resources:
  - peerauthentications
  - httpapispecs
  - httpapispecbindings
  - quotaspecs
  - quotaspecbindings
  - destinationrules
  - envoyfilters
  - gateways
  - serviceentries
  - virtualservices
  - kialis
  - wasmplugins
  - istiooperators
  - proxyconfigs
  - sidecars
  - workloadentries
  - workloadgroups
  - authorizationpolicies
  - requestauthentications
  - telemetries
  verbs:
  - get
  - list
  - watch
- apiGroups: ["rbac.istio.io"] # Istio API group
  resources:
  - peerauthentications
  - httpapispecs
  - httpapispecbindings
  - quotaspecs
  - quotaspecbindings
  - destinationrules
  - envoyfilters
  - gateways
  - serviceentries
  - virtualservices
  - kialis
  - wasmplugins
  - istiooperators
  - proxyconfigs
  - sidecars
  - workloadentries
  - workloadgroups
  - authorizationpolicies
  - requestauthentications
  - telemetries
  verbs:
  - get
  - list
  - watch
- apiGroups: ["authentication.istio.io"] # Istio API group
  resources:
  - peerauthentications
  - httpapispecs
  - httpapispecbindings
  - quotaspecs
  - quotaspecbindings
  - destinationrules
  - envoyfilters
  - gateways
  - serviceentries
  - virtualservices
  - kialis
  - wasmplugins
  - istiooperators
  - proxyconfigs
  - sidecars
  - workloadentries
  - workloadgroups
  - authorizationpolicies
  - requestauthentications
  - telemetries
  verbs:
  - get
  - list
  - watch
- apiGroups: ["mixer.validation.istio.io"] # Istio API group
  resources:
  - peerauthentications
  - httpapispecs
  - httpapispecbindings
  - quotaspecs
  - quotaspecbindings
  - destinationrules
  - envoyfilters
  - gateways
  - serviceentries
  - virtualservices
  - kialis
  - wasmplugins
  - istiooperators
  - proxyconfigs
  - sidecars
  - workloadentries
  - workloadgroups
  - authorizationpolicies
  - requestauthentications
  - telemetries
  verbs:
  - get
  - list
  - watch
- apiGroups: ["extensions.istio.io"] # Istio API group
  resources:
  - wasmplugins
  verbs:
  - get
  - list
  - watch
- apiGroups: ["telemetry.istio.io"] # Istio API group
  resources:
  - telemetries
  verbs:
  - get
  - list
  - watch
- apiGroups: ["kiali.io"] # Istio API group
  resources:
  - kialis
  verbs:
  - get
  - list
  - watch
- apiGroups: ["jaegertracing.io"] # jaeger API group
  resources:
  - jaegers
  verbs:
  - get
  - list
  - watch
- apiGroups: ["rabbitmq.com"] # rabbitmq API group
  resources:
  - binding
  - bindinglist
  - exchange
  - exchangelist
  - federation
  - federationlist
  - permission
  - permissionlist
  - policy
  - policylist
  - queue
  - queuelist
  - schemareplication
  - schemareplicationlist
  - shovel
  - shovellist
  - user
  - userlist
  - vhost
  - vhostlist
  - superstream
  - superstreamlist
  verbs:
  - get
  - list
  - watch
- apiGroups: ["monitoring.coreos.com"] # promstack API group
  resources:
  - servicemonitors
  - alertmanagerconfigs
  - alertmanagers
  - podmonitors
  - probes
  - prometheuses
  - prometheusrules
  - thanosrulers
  verbs:
  - get
  - list
  - watch
- apiGroups: ["velero.io"] # velero API group
  resources:
  - backups
  - backupstoragelocations
  - deletebackuprequests
  - downloadrequests
  - podvolumebackups
  - podvolumerestores
  - resticrepositories
  - restores
  - schedules
  - serverstatusrequests
  - volumesnapshotlocations
  verbs:
  - get
  - list
  - watch
- apiGroups: ["keda.sh"] # keda API group
  resources:
  - scaledjobs
  - scaledobjects
  - triggerauthentications
  verbs:
  - get
  - list
  - watch
  {{- end }}
---
{{- end }}
