{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $flux := $tenantConfig.flux | default dict -}}
{{- if (($flux.tenantReaderRole).enabled) | default true -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-reader
  namespace: {{ $name }}
  labels:
    platform/type: tenant
    {{- include "tenant-provision.labels" $ | nindent 4 }}
rules:
- apiGroups: ["", "apps", "admissionregistration.k8s.io", "autoscaling", "batch", "certificates.k8s.io", "helm.toolkit.fluxcd.io", "metrics.k8s.io, "networking.k8s.io", "notification.toolkit.fluxcd.io", "policy", "rbac.authorization.k8s.io", "source.toolkit.fluxcd.io", "spv.no", "storage.k8s.io", "kyverno.io", "wgpolicyk8s.io" ] # "" indicates the core API group
  resources:
  - bindings
  - componentstatuses
  - configmaps
  - endpoints
  - events
  - limitranges
  - namespaces
  - nodes
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - podtemplates
  - replicationcontrollers
  - resourcequotas
  - secrets
  - serviceaccounts
  - services
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  - customresourcedefinitions
  - apiservices
  - aplogconfs
  - appolicies
  - apusersigs
  - apdoslogconfs
  - apdospolicies
  - dosprotectedresources
  - controllerrevisions
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  - tokenreviews
  - localsubjectaccessreviews
  - selfsubjectaccessreviews
  - selfsubjectrulesreviews
  - subjectaccessreviews
  - horizontalpodautoscalers
  - cronjobs
  - jobs
  - certificatesigningrequests
  - configs
  - leases
  - endpointslices
  - events
  - providers
  - dnsendpoints
  - flowschemas
  - prioritylevelconfigurations
  - helmreleases
  - globalconfigurations
  - policies
  - transportservers
  - virtualserverroutes
  - virtualservers
  - kustomizations
  - nodes
  - pods
  - assign
  - assignmetadata
  - modifyset
  - ingressclasses
  - ingresses
  - networkpolicies
  - runtimeclasses
  - alerts
  - providers
  - receivers
  - poddisruptionbudgets
  - podsecuritypolicies
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  - priorityclasses
  - volumesnapshotclasses
  - volumesnapshotcontents
  - volumesnapshots
  - buckets
  - gitrepositories
  - helmcharts
  - helmrepositories
  - ocirepositories
  - azurekeyvaultsecrets
  - constraintpodstatuses
  - constrainttemplatepodstatuses
  - mutatorpodstatuses
  - csidrivers
  - csinodes
  - csistoragecapacities
  - storageclasses
  - volumeattachments
  - constrainttemplates
  - clusterpolicies
  - clusterreportchangerequests
  - generaterequests
  - reportchangerequests
  - updaterequests
  - clusterpolicyreports
  - policyreports
  verbs:
  - get
  - list
  {{- end }}
---
{{- end }}
