{{- range $name, $tenant := .Values.tenants }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-reader
  namespace: {{ $name }}
  labels:
    platform/type: tenant
    {{- include "tenant-provision.labels" $ | nindent 4 }}
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources:
  - bindings 
  - configmaps 
  - endpoints
  - events 
  - limitranges
  - persistentvolumeclaims
  - pods 
  - podtemplates
  - replicationcontrollers
  - resourcequotas 
  - secrets 
  - serviceaccounts
  - services
  - controllerrevisions
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  - localsubjectaccessreviews
  - horizontalpodautoscalers
  - cronjobs
  - jobs
  - leases 
  - endpointslices
  - events
  - pods 
  - ingresses
  - networkpolicies
  - poddisruptionbudgets 
  - rolebindings 
  - roles
  - volumesnapshots 
  verbs:
  - get
  - list
{{- end }}
