{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $flux := $tenantConfig.flux | default dict -}}
{{- if (($flux.tenantAuditRole).enabled) | default true -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-audit
  namespace: {{ $name }}
  labels:
    platform/type: tenant
    {{- include "tenant-provision.labels" $ | nindent 4 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - bindings
  - componentstatuses
  - configmaps
  - endpoints
  - events
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - podtemplates
  - replicationcontrollers
  - resourcequotas
  - secrets
  - serviceaccounts
  - services
  verbs:
  - get
  - list
- apiGroups: ["apps", "autoscaling", "batch", "policy"] #Other Core functions API groups
  resources:
  - controllerrevisions                    
  - daemonsets                
  - deployments
  - replicasets
  - statefulsets
  - horizontalpodautoscalers
  - cronjobs
  - jobs
  - poddisruptionbudgets
  - podsecuritypolicies
  verbs:
  - get
  - list
- apiGroups: ["admissionregistration.k8s.io", "certificates.k8s.io", "metrics.k8s.io", "networking.k8s.io" ] # Extended core API groups
  resources:
  - mutatingwebhookconfigurations 
  - validatingwebhookconfigurations
  - certificatesigningrequests
  - nodes
  - pods
  - ingressclasses
  - ingresses
  - networkpolicies
  verbs:
  - get
  - list
- apiGroups: ["helm.toolkit.fluxcd.io", "source.toolkit.fluxcd.io", "kustomize.toolkit.fluxcd.io"] # Flux API groups
  resources:
  - helmreleases
  - buckets
  - gitrepositories
  - helmcharts
  - helmrepositories 
  - kustomizations
  verbs:
  - get
  - list
- apiGroups: ["storage.k8s.io"] # Storage API group
  resources:
  - csidrivers
  - csinodes
  - csistoragecapacities
  - storageclasses
  - volumeattachments  
  verbs:
  - get
  - list
- apiGroups: ["rbac.authorization.k8s.io"] # RBAC API group
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - get
  - list
- apiGroups: ["spv.no"] # spv.no API group
  resources:
  - azurekeyvaultsecrets
  verbs:
  - get
  - list
- apiGroups: ["kyverno.io", "wgpolicyk8s.io"] # kyverno API group
  resources:
  - clusterpolicies
  - clusterreportchangerequests
  - generaterequests
  - policies
  - reportchangerequests
  - updaterequests
  - clusterpolicyreports
  - policyreports
  verbs:
  - get
  - list
- apiGroups: ["cert-manager.io"] # wgpolicyk8s API group
  resources:
  - certificaterequests
  - certificates
  - challenges
  - clusterissuers
  - issuers
  - orders
  verbs:
  - get
  - list
- apiGroups: ["install.istio.io", "security.istio.io", "networking.istio.io", "config.istio.io", "rbac.istio.io", "authentication.istio.io", "mixer.validation.istio.io", "monitoring.kiali.io"] # Istio API group
  resources:
  - peerauthentications
  - httpapispecs
  - httpapispecbindings
  - quotaspecs
  - quotaspecbindings
  - destinationrules
  - envoyfilters
  - gateways
  - serviceentries
  - virtualservices
  - kialis
  verbs:
  - get
  - list
- apiGroups: ["jaegertracing.io"] # jaeger API group
  resources:
  - jaegers
  verbs:
  - get
  - list
- apiGroups: ["rabbitmq.com"] # rabbitmq API group
  resources:
  - binding
  - bindinglist
  - exchange
  - exchangelist
  - federation
  - federationlist
  - permission
  - permissionlist
  - policy
  - policylist
  - queue
  - queuelist
  - schemareplication
  - schemareplicationlist
  - shovel
  - shovellist
  - user
  - userlist
  - vhost
  - vhostlist
  - superstream
  - superstreamlist
  verbs:
  - get
  - list
- apiGroups: ["monitoring.coreos.com"] # promstack API group
  resources:
  - servicemonitors
  - alertmanagerconfigs
  - alertmanagers
  verbs:
  - get
  - list
- apiGroups: ["velero.io"] # velero API group
  resources:
  - backups
  - backupstoragelocations
  - deletebackuprequests
  - downloadrequests
  - podvolumebackups
  - podvolumerestores
  - resticrepositories
  - restores
  - schedules
  - serverstatusrequests
  - volumesnapshotlocations
  verbs:
  - get
  - list
  {{- end }}
---
{{- end }}
