{{- range $name, $tenant := .Values.tenants }}
{{- $tenantConfig := $tenant | default dict -}}
{{- $rbac := $tenantConfig.rbac | default dict -}}
{{- if (($rbac.tenantDevRole).enabled) | default false -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-dev-rb
  namespace: {{ $name }}
  labels:
    platform/type: tenant
    aclName: {{ default "." (($rbac.tenantDevRole).aclName) }}
    {{- include "tenant-provision.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-dev
subjects:
- kind: Group
  namespace:  {{ $name }}
  name: {{ default "." (($rbac.tenantDevRole).groupObjectId) }}
  {{- end }}
---
{{- end }}
