{{- range $name, $tenant := .Values.tenants }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-dev
  namespace: {{ $name }}
  labels:
    {{- include "tenant-provision.labels" . | nindent 4 }}
  annotations:
    {{- toYaml . | nindent 4 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - bindings 
  - configmaps 
  - events 
  - limitranges
  - persistentvolumeclaims
  - pods 
  - podtemplates
  - replicationcontrollers
  - resourcequotas 
  - secrets 
  - serviceaccounts
  - services
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  - horizontalpodautoscalers
  - cronjobs
  - jobs
  - events
  - pods 
  - ingresses
  - networkpolicies
  - poddisruptionbudgets 
  - rolebindings 
  - roles
  verbs:
  - get
  - list
  - watch
{{- end }}
