tenants:
  team-test:
    flux:
      path: ./team-tenant
      tenantAdminRole: 
        groupObjectId: "ObjectId"
      tenantAuditRole: 
        groupObjectId: "ObjectId"
      tenantDevRole: 
        groupObjectId: "ObjectId"
      tenantReaderRole: 
        groupObjectId: "ObjectId"
  team-test2:
    flux:
      path: ./team-tenant2
      tenantAdminRole: 
        groupObjectId: "ObjectId"
      tenantAuditRole: 
        groupObjectId: "ObjectId"
      tenantDevRole: 
        groupObjectId: "ObjectId"
      tenantReaderRole: 
        groupObjectId: "ObjectId"